#' Coefficient matrices of the lagged endogenous variables
#'
#' Returns the estimated coefficient matrices of the lagged endogenous
#' variables as a list of matrices each with dimension \eqn{(K \times K)}.
#'
#' Given an estimated VAR(p) of the form: \deqn{ \hat{\bold{y}}_t = \hat{A}_1
#' \bold{y}_{t-1} + \ldots + \hat{A}_p \bold{y}_{t-p} + \hat{C}D_t } the
#' function returns the matrices \eqn{(\hat{A}_1, \ldots, \hat{A}_p)} each with
#' dimension \eqn{(K \times K)} as a list object.
#'
#' @param x An object of class \sQuote{\code{varest}}, generated by
#' \command{VAR()}.
#' @return A list object with coefficient matrices for the lagged endogenous
#' variables.
#' @author Bernhard Pfaff
#' @seealso \code{\link{Bcoef}}, \code{\link{VAR}}
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' Acoef(var.2c)
#'
#' @export Acoef
"Acoef" <- function (x)
{
    if (!is(x, "varest")) {
        stop("\nPlease provide an object of class 'varest', generated by 'var()'.\n")
    }
    K <- x$K
    p <- x$p
    A <- Bcoef(x)[, 1:(K*p)]
    As <- list()
    start <- seq(1, p * K, K)
    end <- seq(K, p * K, K)
    for (i in 1:p) {
        As[[i]] <- matrix(A[, start[i]:end[i]], nrow = K, ncol = K)
        rownames(As[[i]]) <- rownames(A)
        colnames(As[[i]]) <- colnames(A[, start[i]:end[i]])
    }
    return(As)
}

#A <- function(x){
#  .Deprecated("Acoef", package = "vars", msg = "Function 'A' is deprecated; use 'Acoef' instead.\nSee help(\"vars-deprecated\") and help(\"A-deprecated\") for more information.")
#  Acoef(x = x)
#}
