#' Coefficient matrix of an estimated VAR(p)
#'
#' Returns the estimated coefficients of a VAR(p) as a matrix.
#'
#' Given an estimated VAR of the form: \deqn{ \hat{\bold{y}}_t = \hat{A}_1
#' \bold{y}_{t-1} + \ldots + \hat{A}_p \bold{y}_{t-p} + \hat{C}D_t } the
#' function returns the matrices \eqn{(\hat{A}_1 | \ldots | \hat{A}_p |
#' \hat{C})} as a matrix object.
#'
#' @param x An object of class \sQuote{\code{varest}}, generated by
#' \command{VAR()}.
#' @return A matrix holding the estimated coefficients of a VAR.
#' @author Bernhard Pfaff
#' @seealso \code{\link{Acoef}}, \code{\link{VAR}}
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' Bcoef(var.2c)
#'
#' @export Bcoef
"Bcoef" <-
function(x){
  if(!is(x, "varest")){
    stop("\nPlease provide an object of class 'varest', generated by 'var()'.\n")
  }
  y.names <- colnames(x$datamat[, c(1 : x$K)])
  Z <- x$datamat[, -c(1 : x$K)]
  B <- matrix(0, nrow = x$K, ncol = ncol(Z))
  if(is.null(x$restriction)){
    for(i in 1 : x$K){
      B[i, ] <- coef(x$varresult[[i]])
    }
  }else if(!(is.null(x$restriction))){
    for(i in 1 : x$K){
      restrictions <- x$restrictions
      restrictions[i, restrictions[i, ] == TRUE] <- coef(x$varresult[[i]])
      temp <- restrictions[i, ]
      B[i, ] <- temp
    }
  }
  colnames(B) <- colnames(Z)
  rownames(B) <- y.names
  return(B)
}
B <- function(x){
  .Deprecated("Bcoef", package = "vars", msg = "Function 'B' is deprecated; use 'Acoef' instead.\nSee help(\"vars-deprecated\") and help(\"B-deprecated\") for more information.")
  Bcoef(x = x)
}
