#' Fit method for objects of class varest or vec2var
#'
#' Returns the fitted values of a VAR(p)-model for objects generated by
#' \command{VAR()} or \command{vec2var()}. For objects of class varest the
#' fitted.values-method is applied to the list element \code{varresult}, which
#' is itself a list of \code{lm}-objects.
#'
#'
#' @aliases fitted fitted.values fitted.varest fitted.vec2var
#' @param object An object of class \sQuote{\code{varest}}; generated by
#' \command{VAR()}, or an object of class \sQuote{\code{vec2var}}; generated by
#' \command{vec2var()}.
#' @param \dots Currently not used.
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}, \code{\link{vec2var}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' fitted(var.2c)
#'
#' @export fitted.vec2var
"fitted.vec2var" <-
function(object, ...){
  if (!is(object, "vec2var")) {
    stop("\nPlease, provide object of class 'vec2var' as 'object'.\n")
  }
  resids <- resid(object)
  fitted <- object$datamat[, colnames(object$y)] - resids
  colnames(fitted) <- paste("fit of", colnames(object$y))
  return(fitted)
}
