#' Normality, multivariate skewness and kurtosis test
#'
#' This function computes univariate and multivariate Jarque-Bera tests and
#' multivariate skewness and kurtosis tests for the residuals of a VAR(p) or of
#' a VECM in levels.
#'
#' Multivariate and univariate versions of the Jarque-Bera test are applied to
#' the residuals of a VAR. The multivariate version of this test is computed by
#' using the residuals that are standardized by a Choleski decomposition of the
#' variance-covariance matrix for the centered residuals. Please note, that in
#' this case the test result is dependant upon the ordering of the variables.
#'
#' @param x Object of class \sQuote{\code{varest}}; generated by
#' \command{VAR()}, or an object of class \sQuote{\code{vec2var}}; generated by
#' \command{vec2var()}.
#' @param multivariate.only If \code{TRUE} (the default), only multivariate
#' test statistics are computed.
#' @return A list of class \sQuote{\code{varcheck}} with the following elements
#' is returned:\cr
#'
#' \item{resid}{A matrix of the residuals.} \item{jb.uni}{A list of elements
#' with class attribute \sQuote{\code{htest}} containing the univariate
#' Jarque-Bera tests. This element is only returned if \code{multivariate.only
#' = FALSE} is set.} \item{jb.mul}{A list of elements with class attribute
#' \sQuote{\code{htest}}.} containing the mutlivariate Jarque-Bera test, the
#' multivariate Skewness and Kurtosis tests.
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}, \code{\link{vec2var}}, \code{\link{plot}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Jarque, C. M. and A. K. Bera (1987), A test for normality of observations
#' and regression residuals, \emph{International Statistical Review},
#' \bold{55}: 163-172.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' normality.test(var.2c)
#'
#' @export
"normality.test" <-
function(x, multivariate.only = TRUE){
  if(!(is(x, "varest") || is(x, "vec2var"))){
    stop("\nPlease provide an object of class 'varest', generated by 'var()', or an object of class 'vec2var' generated by 'vec2var()'.\n")
  }
  obj.name <- deparse(substitute(x))
  K <- x$K
  obs <- x$obs
  resid <- resid(x)
  resids <- scale(resid, scale=FALSE)
  ## Jarque Bera Test (multivariate)
  jbm.resids <- .jb.multi(resids, obs = obs, K = K, obj.name = obj.name)
  if(multivariate.only){
    result <- list(resid = resid, jb.mul = jbm.resids)
  } else {
    ## Jarque Bera Test (univariate)
    jbu.resids <- apply(resids, 2, function(x) .jb.uni(x, obs = obs))
    for(i in 1 : K)
      jbu.resids[[i]][5] <- paste("Residual of", colnames(resids)[i], "equation")
    result <- list(resid = resid, jb.uni = jbu.resids, jb.mul = jbm.resids)
  }
  class(result) <- "varcheck"
  return(result)
}
#normality <- function(x, multivariate.only = TRUE){
#  .Deprecated("normality.test", package = "vars", msg = "Function 'normality' is deprecated; use 'normality.test' instead.\nSee help(\"vars-deprecated\") and help(\"normality-deprecated\") for more information.")
#  normality.test(x = x, multivariate.only = multivariate.only)
#}
