#'
#' @param x An object of class \sQuote{\code{varest}}, generated by
#' \command{VAR()}, or an object of class \sQuote{\code{svarest}}, generated by
#' \command{SVAR()}, or an object of class \sQuote{\code{svecest}}, generated
#' by \command{SVEC()}, or an object of class \sQuote{\code{vec2var}},
#' generated by \command{vec2var()}.
#' @param nstep An integer specifying the number of moving error coefficient
#' matrices to be calculated.
#' @param ... Currently not used.
#'
#' @export
"Phi.svarest" <-
function(x, nstep = 10, ...){
  if(!is(x, "svarest")){
    stop("\nPlease provide an object of class 'svarest', generated by 'SVAR()'.\n")
  }
  nstep <- abs(as.integer(nstep))
  Ainv <- solve(x$A)
  Phi <- Phi(x$var, nstep = nstep)
  for(i in 1: dim(Phi)[3]){
    Phi[, , i] <- Phi[, , i] %*% Ainv %*% x$B
  }
  return(Phi)
}
