#' Predict method for objects of class varest and vec2var
#'
#' Forecating a VAR object of class \sQuote{\code{varest}} or of class
#' \sQuote{\code{vec2var}} with confidence bands.
#'
#' The \code{n.ahead} forecasts are computed recursively for the estimated VAR,
#' beginning with \eqn{h = 1, 2, \ldots, n.ahead}:
#'
#' \deqn{ \bold{y}_{T+1 | T} = A_1 \bold{y}_T + \ldots + A_p \bold{y}_{T+1-p} +
#' C D_{T+1} }
#'
#' The variance-covariance matrix of the forecast errors is a function of
#' \eqn{\Sigma_u} and \eqn{\Phi_s}.
#'
#' @name predict
#' @aliases predict predict.varest predict.vec2var print.varprd
#' @param object An object of class \sQuote{\code{varest}}; generated by
#' \command{VAR()}, or an object of class \sQuote{\code{vec2var}}; generated by
#' \command{vec2var()}.
#' @param n.ahead An integer specifying the number of forecast steps.
#' @param ci The forecast confidence interval
#' @param dumvar Matrix for objects of class \sQuote{\code{vec2var}} or
#' \sQuote{\code{varest}}, if the \code{dumvar} argument in \command{ca.jo()}
#' has been used or if the \code{exogen} argument in \command{VAR()} has been
#' used, respectively. The matrix should have the same column dimension as in
#' the call to \command{ca.jo()} or to \command{VAR()} and row dimension equal
#' to \code{n.ahead}.
#' @param \dots Currently not used.
#' @return A list with class attribute \sQuote{\code{varprd}} holding the
#' following elements:\cr
#'
#' \item{fcst}{A list of matrices per endogenous variable containing the
#' forecasted values with lower and upper bounds as well as the confidence
#' interval.} \item{endog}{Matrix of the in-sample endogenous variables.}
#' \item{model}{The estimated VAR \code{object}.} \item{exo.fcst}{If applicable
#' provided values of exogenous variables, otherwise \code{NULL}.}
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}, \code{\link{vec2var}}, \code{\link{plot}},
#' \code{\link{fanchart}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' predict(var.2c, n.ahead = 8, ci = 0.95)
#'
NULL