#' residuals.varest
#' @param object An object of class ‘varest’; generated by VAR(), 
#' or an object of class ‘vec2var’; generated by vec2var()
#' @param \dots Currently not used.
#' @importFrom stats residuals
#' @export
"residuals.varest" <-
function(object, ...){
  return(sapply(object$varresult, residuals))
}
