#' Eigenvalues of the companion coefficient matrix of a VAR(p)-process
#'
#' Returns a vector of the eigenvalues of the companion coefficient matrix.
#'
#' Any VAR(p)-process can be written in a first-order vector autoregressive
#' form: the companion form. A VAR(p)-process is stable, if its reverse
#' characteristic polynomial:
#'
#' \deqn{ \det(I_K - A_1 z - \cdots - A_p z^p) \neq 0 \; \hbox{for} \; |z| \le
#' 1 \; , }
#'
#' has no roots in or on the complex circle. This is equivalent to the
#' condition that all eigenvalues of the companion matrix \eqn{A} have modulus
#' less than 1. The function \code{roots()}, does compute the eigen values of
#' the companion matrix \eqn{A} and returns by default their moduli.
#'
#' @param x An object of class \sQuote{\code{varest}}, generated by
#' \command{VAR()}.
#' @param modulus Logical, set to \code{TRUE} for returning the modulus.
#' @return A vector object with the eigen values of the companion matrix, or
#' their moduli (default).
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' roots(var.2c)
#'
#' @export
"roots" <-
function(x, modulus = TRUE){
  if(!is(x, "varest")){
    stop("\nPlease provide an object of class 'varest', generated by 'VAR()'.\n")
  }
  K <- x$K
  p <- x$p
  A <- unlist(Acoef(x))
  companion <- matrix(0, nrow = K * p, ncol = K * p)
  companion[1:K, 1:(K * p)] <- A
  if(p > 1){
    j <- 0
    for( i in (K + 1) : (K*p)){
      j <- j + 1
      companion[i, j] <- 1
    }
  }
  roots <- eigen(companion)$values
  if(modulus) roots <- Mod(roots)
  return(roots)
}
