#' Unite tibble objects generated by fredr (CRAN)
#'
#' @param fredr_list the list of tibble objects from fredr
#' @param var_name the name list of variables
#' 
#' @importFrom stats setNames
#' @importFrom dplyr select left_join
#' @export unite_fredr
#' 
#' @examples
#' \dontrun{
#' library(fredr)
#' library(tidyverse)
#' # Set your FRED API Key
#' fredr_set_key("d88c682c8274047b72e7e64da46a7801")
#' #fredr_set_key("abcdefghijklmnopqrstuvwxyz")
#' #freq_flag <- "m" # Monthly
#' freq_flag <- "q" # Quarterly
#' #freq_flag <- "a" # Annual
#' # In FRED, the start and the end of the observation period
#' start1_date <- "2018-01-01"
#' end1_date <- Sys.Date()
#' 
#' # Real Private Final Consumption Expenditure for United States
#' # https://fred.stlouisfed.org/series/NAEXKP02USQ189S
#' us_prv_c <- fredr_series_observations(
#' series_id = "NAEXKP02USQ189S",
#' observation_start = as.Date(start1_date),
#' observation_end = as.Date(end1_date),
#' frequency = freq_flag,
#' units = "log"
#' )
#' 
#' # Real Government Final Consumption Expenditure for United States
#' # https://fred.stlouisfed.org/series/NAEXKP03USQ652S
#' us_gov_e <- fredr_series_observations(
#' series_id = "NAEXKP03USQ652S",
#' observation_start = as.Date(start1_date),
#' observation_end = as.Date(end1_date),
#' frequency = freq_flag,
#' units = "log"
#' )
#' 
#' # GDP Deflator for United States
#' # https://fred.stlouisfed.org/series/USAGDPDEFQISMEI
#' us_def <- fredr_series_observations(
#' series_id = "USAGDPDEFQISMEI",
#' observation_start = as.Date(start1_date),
#' observation_end = as.Date(end1_date),
#' frequency = freq_flag,
#' units = "log"
#' )
#' 
#' fredr_list <- list(us_prv_c, us_gov_e, us_def)
#' var_name <- c("priv_c", "gov_e", "defl")
#' us_macro <- unite_fredr(fredr_list, var_name)  
#' print(us_macro)
#' }
"unite_fredr" <- function(fredr_list, var_name){
  num_epoch <- length(fredr_list)
  tmp_list <- list()

  # Pick up "date" and "value" and set names
  for (ii in 1:num_epoch) {
#    browser()
    col_names <- c("date", var_name[ii])
    # https://stackoverflow.com/questions/36520813/r-dplyr-rename-and-select-using-string-variable
    fredr_list[[ii]] |>  dplyr::select("date", "value") |>
      stats::setNames(col_names) -> tmp
    tmp_list <- c(tmp_list, list(tmp))
  }
#  print(tmp_list)

  # Joint "fredr tibbles" by left_joint
  fredr_united <- NULL
#  browser()
  for (ii in 1:num_epoch) {
    if(is.null(fredr_united)){
      fredr_united <- tmp_list[[ii]]
    } else {
#      browser()
      dplyr::left_join(fredr_united, tmp_list[[ii]]) -> fredr_united
    }
  }
#  print(fredr_united)
  return(fredr_united)
}
