#' Coefficient method for objects of class varest
#'
#' Returns the coefficients of a VAR(p)-model for objects generated by
#' \command{VAR()}. Thereby the coef-method is applied to the summary of the
#' list element \code{varresult}, which is itself a list of
#' \code{summary.lm}-objects.
#'
#'
#' @aliases coef coefficients coef.varest
#' @param object An object of class \sQuote{\code{varest}}; generated by
#' \command{VAR()}
#' @param \dots Currently not used.
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' coef(var.2c)
#'





#' Predict method for objects of class varest and vec2var
#'
#' Forecating a VAR object of class \sQuote{\code{varest}} or of class
#' \sQuote{\code{vec2var}} with confidence bands.
#'
#' The \code{n.ahead} forecasts are computed recursively for the estimated VAR,
#' beginning with \eqn{h = 1, 2, \ldots, n.ahead}:
#'
#' \deqn{ \bold{y}_{T+1 | T} = A_1 \bold{y}_T + \ldots + A_p \bold{y}_{T+1-p} +
#' C D_{T+1} }
#'
#' The variance-covariance matrix of the forecast errors is a function of
#' \eqn{\Sigma_u} and \eqn{\Phi_s}.
#'
#' @aliases predict predict.varest predict.vec2var print.varprd
#' @param object An object of class \sQuote{\code{varest}}; generated by
#' \command{VAR()}, or an object of class \sQuote{\code{vec2var}}; generated by
#' \command{vec2var()}.
#' @param n.ahead An integer specifying the number of forecast steps.
#' @param ci The forecast confidence interval
#' @param dumvar Matrix for objects of class \sQuote{\code{vec2var}} or
#' \sQuote{\code{varest}}, if the \code{dumvar} argument in \command{ca.jo()}
#' has been used or if the \code{exogen} argument in \command{VAR()} has been
#' used, respectively. The matrix should have the same column dimension as in
#' the call to \command{ca.jo()} or to \command{VAR()} and row dimension equal
#' to \code{n.ahead}.
#' @param \dots Currently not used.
#' @return A list with class attribute \sQuote{\code{varprd}} holding the
#' following elements:\cr
#'
#' \item{fcst}{A list of matrices per endogenous variable containing the
#' forecasted values with lower and upper bounds as well as the confidence
#' interval.} \item{endog}{Matrix of the in-sample endogenous variables.}
#' \item{model}{The estimated VAR \code{object}.} \item{exo.fcst}{If applicable
#' provided values of exogenous variables, otherwise \code{NULL}.}
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}, \code{\link{vec2var}}, \code{\link{plot}},
#' \code{\link{fanchart}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' predict(var.2c, n.ahead = 8, ci = 0.95)
#'





#' Residuals method for objects of class varest and vec2var
#'
#' Returns the residuals of a VAR(p)-model or for a VECM in levels. For the
#' former class the residuals-method is applied to the list element
#' \code{varresult}, which is itself a list of \code{lm}-objects.
#'
#'
#' @aliases residuals resid residuals.varest residuals.vec2var
#' @param object An object of class \sQuote{\code{varest}}; generated by
#' \command{VAR()}, or an object of class \sQuote{\code{vec2var}}; generated by
#' \command{vec2var()}
#' @param \dots Currently not used.
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}, \code{\link{vec2var}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' \dontrun{
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' resid(var.2c)
#' }
#'





#' Summary method for objects of class varest, svarest and svecest
#'
#' 'summary' methods for class '"varest"', '"svarest"' and '"svecest"'.
#'
#'
#' @aliases summary summary.varest summary.svarest summary.svecest print.varsum
#' print.svarsum print.svecsum
#' @param object Object of class \sQuote{\code{varest}}, usually, a result of a
#' call to \code{VAR}, or object of class \sQuote{\code{svarest}}, usually, a
#' result of a call to \code{SVAR}, or object of class \sQuote{\code{svecest}},
#' usually, a result of a call to \code{SVEC}.
#' @param equations Character vector of endogenous variable names for which
#' summary results should be returned. The default is \code{NULL} and results
#' are returned for all equations in the VAR.
#' @param x Object with class attribute \sQuote{varsum}, \sQuote{svarsum}.
#' @param digits the number of significant digits to use when printing.
#' @param signif.stars logical. If 'TRUE', \sQuote{significance stars} are
#' printed for each coefficient.
#' @param \dots further arguments passed to or from other methods.
#' @return Returns either a list with class attribute \code{varsum} which
#' contains the following elements:
#'
#' \item{names}{Character vector with the names of the endogenous correlation
#' matrix of VAR residuals.} \item{logLik}{Numeric, value of log Likelihood.}
#' \item{obs}{Integer, sample size.} \item{roots}{Vector, roots of the
#' characteristic polynomial.} \item{type}{Character vector, deterministic
#' regressors included in VAR:} \item{call}{Call, the initial call to
#' \code{VAR}.}
#'
#' Or a list with class attribute \code{svarsum} which contains the following
#' elements:
#'
#' \item{type}{Character, the type of SVAR-model.} \item{A}{Matrix, estimated
#' coefficients for A matrix.} \item{B}{Matrix, estimated coefficients for B
#' matrix.} \item{Ase}{Matrix, standard errors for A matrix.}
#' \item{Bse}{Matrix, standard errors for B matrix.} \item{LRIM}{Matrix,
#' long-run impact coefficients for \code{BQ}.} \item{Sigma.U}{Matrix,
#' variance/covariance of reduced form residuals.} \item{logLik}{Numeric, value
#' of log-Likelihood.} \item{LR}{htest, LR result of over-identification test.}
#' \item{obs}{Integer, number of observations used.} \item{opt}{List, result of
#' \code{optim()}.} \item{iter}{Integer, the count of iterations.}
#' \item{call}{Call, the call to \code{SVAR()}.}
#'
#' Or a list with class attribute \code{svecsum} which contains the following
#' elements:
#'
#' \item{type}{Character, the type of SVEC-model.} \item{SR}{Matrix,
#' contemporaneous impact matrix.} \item{LR}{Matrix, long-run impact matrix.}
#' \item{SRse}{Matrix, standard errors for SR matrix.} \item{LRse}{Matrix,
#' standard errors for LR matrix.} \item{Sigma.U}{Matrix, variance/covariance
#' of reduced form residuals.} \item{logLik}{Numeric, value of log-Likelihood.}
#' \item{LRover}{htest, LR result of over-identification test.}
#' \item{obs}{Integer, number of observations used.} \item{r}{Integer,
#' co-integration rank of VECM.} \item{iter}{Integer, the count of iterations.}
#' \item{call}{Call, the call to \code{SVEC()}.}
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}, \code{\link{SVAR}}, \code{\link{SVEC}}
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' ## summary-method for varest
#' var.2c <- VAR(Canada, p = 2 , type = "const")
#' summary(var.2c)
#' ## summary-method for svarest
#' amat <- diag(4)
#' diag(amat) <- NA
#' amat[2, 1] <- NA
#' amat[4, 1] <- NA
#' ## Estimation method scoring
#' svar.a <- SVAR(x = var.2c, estmethod = "scoring", Amat = amat, Bmat = NULL,
#' max.iter = 100, maxls = 1000, conv.crit = 1.0e-8)
#' summary(svar.a)
#' ## summary-method for svecest
#' vecm <- ca.jo(Canada[, c("prod", "e", "U", "rw")], type = "trace",
#'               ecdet = "trend", K = 3, spec = "transitory")
#' SR <- matrix(NA, nrow = 4, ncol = 4)
#' SR[4, 2] <- 0
#' LR <- matrix(NA, nrow = 4, ncol = 4)
#' LR[1, 2:4] <- 0
#' LR[2:4, 4] <- 0
#' svec.b <- SVEC(vecm, LR = LR, SR = SR, r = 1, lrtest = FALSE, boot =
#' FALSE)
#' summary(svec.b)
#'





#' Deprecated Functions in package vars
#'
#' These functions are provided for compatibility with older versions of
#' package vars only, and may be defunct as soon as the next release.
#'
#' 'A' is a deprecated synonym for 'Acoef'.\cr 'arch' is a deprecated synonym
#' for 'arch.test'.\cr 'B' is a deprecated synonym for 'Bcoef'.\cr 'normality'
#' is a deprecated synonym for 'normality.test'.\cr 'serial' is a deprecated
#' synonym for 'serial.test'.
#'
#' @name vars-deprecated
#' @aliases vars-deprecated A B arch normality serial
#' @docType data
#' @seealso \code{\link{Acoef}}, \code{\link{arch.test}}, \code{\link{Bcoef}},
#' \code{\link{normality.test}}, \code{\link{serial.test}}
#' @keywords regression



