
#' Coefficient method for objects of class varest
#'
#' Returns the coefficients of a VAR(p)-model for objects generated by
#' \command{VAR()}. Thereby the coef-method is applied to the summary of the
#' list element \code{varresult}, which is itself a list of
#' \code{summary.lm}-objects.
#'
#'
#' @aliases coef coefficients coef.varest
#' @param object An object of class \sQuote{\code{varest}}; generated by
#' \command{VAR()}
#' @param \dots Currently not used.
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' coef(var.2c)
#'






#' Residuals method for objects of class varest and vec2var
#'
#' Returns the residuals of a VAR(p)-model or for a VECM in levels. For the
#' former class the residuals-method is applied to the list element
#' \code{varresult}, which is itself a list of \code{lm}-objects.
#'
#'
#' @aliases residuals resid residuals.varest residuals.vec2var
#' @param object An object of class \sQuote{\code{varest}}; generated by
#' \command{VAR()}, or an object of class \sQuote{\code{vec2var}}; generated by
#' \command{vec2var()}
#' @param \dots Currently not used.
#' @author Bernhard Pfaff
#' @seealso \code{\link{VAR}}, \code{\link{vec2var}}
#' @references Hamilton, J. (1994), \emph{Time Series Analysis}, Princeton
#' University Press, Princeton.
#'
#' Lütkepohl, H. (2006), \emph{New Introduction to Multiple Time Series
#' Analysis}, Springer, New York.
#' @keywords regression
#' @examples
#'
#' \dontrun{
#' data(Canada)
#' var.2c <- VAR(Canada, p = 2, type = "const")
#' resid(var.2c)
#' }
#'










#' Deprecated Functions in package vars
#'
#' These functions are provided for compatibility with older versions of
#' package vars only, and may be defunct as soon as the next release.
#'
#' 'A' is a deprecated synonym for 'Acoef'.\cr 'arch' is a deprecated synonym
#' for 'arch.test'.\cr 'B' is a deprecated synonym for 'Bcoef'.\cr 'normality'
#' is a deprecated synonym for 'normality.test'.\cr 'serial' is a deprecated
#' synonym for 'serial.test'.
#'
#' @name vars-deprecated
#' @aliases vars-deprecated A B arch normality serial
#' @docType data
#' @seealso \code{\link{Acoef}}, \code{\link{arch.test}}, \code{\link{Bcoef}},
#' \code{\link{normality.test}}, \code{\link{serial.test}}
#' @keywords regression



